### PR TITLE
Big Update & Bump to New Version

### PR DESCRIPTION
**Pull request by cachecleanerjeet**
- Using FFMPEG (WASM)
https://github.com/ffmpegwasm/ffmpeg.wasm
- Can convert into any bit
- Proxy updated
- Used fetch insted of XHR
- Used async await for promises
- Notification toast box implimented, because counting the progress (Download,  Conversion) can be hard
- Some fixes

### CODE REVIEW

**Review by naqushab — APPROVED** [review]
Great work as always! One suggestion, you should add more about yourself in the Readme and the projects that the extension uses in the backend.

**Comment by naqushab** [comment]
Let me know if you want to do it separately in a PR and I'll merge this to mainline.

**Comment by cachecleanerjeet** [comment]
> Great work as always! One suggestion, you should add more about yourself in the Readme and the projects that the extension uses in the backend.

I made that cf worker only for this project, okay will add a readme for proxy

**Comment by cachecleanerjeet** [comment]
You, merge this first. Then I will add some readme for backend.

**Pull request merged**
