### PR TITLE
changed api & cors extension is optional now

### PR DESCRIPTION
**Pull request by cachecleanerjeet**
**Changelog:**

1. Shifted
https://github.com/cyberboysumanjay/JioSaavnAPI
to
https://github.com/cachecleanerjeet/JiosaavnAPI

2. No need for CORS Extension

Proxied album & download url using cloudflare worker & added access-control-allow-origin header. So,no need for cors disable extension. Proxy script located on <tt>proxy</tt> directory.

3. Ads are visible occasionally, @naqushab  look at this issue

4. Because 192 kbps are now not available on jiosaavn so, whenever someone download in 192kbps they will automatically download 128 kbps.

5. Api server is fast now

**By [TUHIN](https://github.com/cachecleanerjeet)**
**27/09/2020**

### CODE REVIEW

**Comment by naqushab** [comment]
Wow, this is awesome @cachecleanerjeet . And literally in no time. Did you test out the extension after the change?
I will review the code by end of the day. Also please add your name in the README.md; this is a significant contribution and people should be aware of it.

**Comment by cachecleanerjeet** [comment]
Yeah i tested everything . everything is perfectly working , but sometimes ads are coming..  And pls sir you update the readme 😃😃

**Comment by naqushab** [comment]
@cachecleanerjeet will do.. thanks for this great contribution. I am merging the change.

**Comment by cachecleanerjeet** [comment]
thanks again

**Pull request merged**
